### ISSUE TITLE
Add a "Fork me on github" banner

### ISSUE THREAD

**Issue by Spensaur-K** [Spensaur-K/mlfq-viz#60]
Add a github banner to link to this repository
![image](https://user-images.githubusercontent.com/4724387/31919231-320bc326-b81e-11e7-8393-083b3f8aff4b.png)
https://github.com/blog/273-github-ribbons

**Comment by andyvh** [comment]
I can do this!

**Comment by andyvh** [comment]
I don't see anything about how to test this in the README though... I'm making the pull request just so people don't steal this out from under me.

**Comment by Spensaur-K** [comment]
Thanks :) .
 We don't have automated testing, however, @EvanGee has just created some instructions on how to build

**Comment by andyvh** [comment]
So I guess I'm not needed here?

**Comment by Spensaur-K** [comment]
@andyvh Instructions are just how to build the project in general, we have not implemented the banner.
